### ISSUE TITLE
Interesting Zynq boards

### ISSUE THREAD

**Issue by jeanminet** [Koheron/zynq-sdk#17]
* [PicoZed](http://zedboard.org/product/picozed)
* [Parallella](https://www.parallella.org/)
* [Mars ZX2](http://www.enclustra.com/en/products/system-on-chip-modules/mars-zx2/)

**Comment by minjungkh** [comment]
* [Snickerdoodle](http://krtkl.com/)

**Comment by minjungkh** [comment]
* Dave Embedded Systems' [Bora](http://www.dave.eu/products/som/xilinx/zynq-XC7Z010-XC7Z020_bora)
