### ISSUE TITLE
minor cell improvement

### ISSUE THREAD

**Issue by pavel-demin** [Koheron/zynq-sdk#29]
Hello,

Your `averaging.tcl` and `spectrum.tcl` code looks impressive!

I propose to make this code slightly cleaner by removing all the `list` commands and all the backslashes.

If you replace `foreach {prop_name prop_value} $cell_props` with `foreach {prop_name prop_value} [subst $cell_props]` and `foreach {local_name remote_name} $cell_ports` with `foreach {local_name remote_name} [subst $cell_ports]` in `scripts/project.tcl`, then all the `[list ...]` blocks could be replaced with `{...}` without backslashes.

Best regards,

Pavel

**Comment by jeanminet** [comment]
Hello Pavel,

Thanks a lot for the tip ! 
I was starting to get crazy with all this backslashes...

**Comment by jeanminet** [comment]
#30

**Comment by pavel-demin** [comment]
Correction.

The right command is `[uplevel 1 [list subst $cell_props]]`

**Comment by jeanminet** [comment]
It works ! 
Thanks again !
