### ISSUE TITLE
Install Vivado HLx 2015.4 on Ubuntu 14.04

### ISSUE THREAD

**Issue by jeanminet** [Koheron/zynq-sdk#37]
The High Level Synthesis Tool is now available in all versions of vivado (including the free WebPACK version). To reflect this change, Vivado has been renamed to Vivado HLx. Here is how to install the free version of Vivado HLx on Ubuntu:

1) Go to the Xilinx Download Page: 
http://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools/2015-4.html

2) Select `Vivado HLx 2015.4 WebInstall for Linux with SDK`

3) Enter your Xilinx credentials and download the executable

4) Run the executable:
```
cd ~/Downloads/
chmod +x Xilinx_Vivado_SDK_2015.4_1118_2_Lin64.bin
sudo ./Xilinx_Vivado_SDK_2015.4_1118_2_Lin64.bin
```

5) Follow the instructions

![screenshot from 2015-12-08 18 14 28](https://cloud.githubusercontent.com/assets/1735094/11662560/a217b822-9dd7-11e5-9349-4990c54cf5d3.png)

:warning: don't forget to select `Software Development Kit`

![screenshot from 2015-12-08 18 14 49](https://cloud.githubusercontent.com/assets/1735094/11662569/a82cb9f6-9dd7-11e5-8b72-70af6ac3a55c.png)

![screenshot from 2015-12-08 18 15 14](https://cloud.githubusercontent.com/assets/1735094/11662574/ac47bfea-9dd7-11e5-99ff-1dcc2530e4d3.png)

**Comment by tvanderbruggen** [comment]
In case the login fails in the web based install.
1) On the Xilinx download page select the full package `Vivado HLx 2015.4: Full Installer For Linux Single File `.

2) Run:
```
cd ~/Downloads/
tar -xvzf Xilinx_Vivado_SDK_Lin_2015.4_1118_2.tar.gz
cd Xilinx_Vivado_SDK_Lin_2015.4_1118_2/
chmod +x xsetup
bash xsetup
```
3) Follow the install instructions as describe above

**Comment by tvanderbruggen** [comment]
To load the licence, do not use the licence manager that prompts at the end of the install but open Vivado and use the licence manager from there (in the help menu).
