### ISSUE TITLE
be careful to use git clone command...

### ISSUE THREAD

**Issue by llombard** [Koheron/zynq-sdk#84]
... otherwise you get
`make: *** No rule to make target `.git/refs/heads', needed by `tmp/blink.version'.  Stop.
Command-line invocation:
	"make NAME=blink zip"
`
when trying to make the project (.git folder is not included in zip file repository)

**Comment by jeanminet** [comment]
Thank you !

The Makefile use the `.git` folder for versioning.
I edited the Makefile to set the version to `default` when the `git rev-parse --short HEAD` command fails : 7ff9ff0b

This should work now.
