### ISSUE TITLE
so what's next?

### ISSUE THREAD

**Issue by llombard** [Koheron/zynq-sdk#87]
Once the 3 commands are performed
`$ make NAME=<project> zip`
`$ make NAME=<project>`
`$ sudo bash scripts/image.sh <project>`
well... what's next?

**Comment by jeanminet** [comment]
We are working on the documentation.

Note that you can download the latest release of the SD card image on this link (https://github.com/Koheron/zynq-sdk/releases). The image contains a Ubuntu distribution with the `oscillo` and `spectrum` applications pre-installed.

You can build this image by running the following commands: 
```
$ make NAME=oscillo
$ make NAME=spectrum zip
$ sudo bash scripts/image.sh oscillo
```

An image called `oscillo-<version>.img` should be created on the root folder of your repository.

#### Burn the SD card image on Ubuntu 14.04:

* Insert a SD card on your SD card reader
* Right-click `oscillo-<version>.img` and open it with Disk Image Writer

:warning: don't select your primary disk !

![screenshot from 2016-03-02 14 34 00](https://cloud.githubusercontent.com/assets/1735094/13461725/a28062b6-e083-11e5-9b08-4ce7300755d7.png)

![screenshot from 2016-03-02 14 34 20](https://cloud.githubusercontent.com/assets/1735094/13461730/a6b90a9a-e083-11e5-81ea-b4784f5bb00e.png)

Once the image is written on the SD Card, you can insert in on the board and follow this tutorial:
http://www.koheron.com/products/lase/getting-started/
